version: '2'
services:
  test35:
    build:
      context: .
      dockerfile: docker/test_py35/Dockerfile
    depends_on:
      - basex.docker
  test36:
    build:
      context: .
      dockerfile: docker/test_py36/Dockerfile
    depends_on:
      - basex.docker

  basex.docker:
    build: docker/basex
    expose:
      - "1984"
      - "8984"
